### PR TITLE
Add autoload definition, fixes #97

### LINKED ISSUE #97: Error loading autoloads: (void-function evil-define-command)
I see this issue after updating to latest code. Look like it's the same as https://github.com/emacs-evil/evil-surround/issues/82

### PR DESCRIPTION
**Pull request by nitros12**
Fixes #97

### CODE REVIEW

**Comment by kshenoy** [comment]
I made the same edits in my evil-matchit.el (which I grabbed from melpa) but it doesn't seem to work. Do I need any other edits elsewhere?

**Comment by TheBB** [comment]
You have to regenerate the autoloads file.

**Comment by kshenoy** [comment]
I'm fairly new to all of this so apologies for any dumb questions/statements. Having said that, I thought `(package-initialize)` generates autoloads?

**Comment by TheBB** [comment]
No, it just reads and loads all the autoloads files. They are generated at package installation time. You can probably use package-generate-autoloads with the appropriate arguments, or make the corresponding edit in the existing autoloads file (perhaps easier).

**Comment by kshenoy** [comment]
Ah, ok. Thanks, it works now :)

**Comment by redguardtoo** [comment]
Thanks

**Pull request merged**
